--- docker-baseimage-alpine/Dockerfile	2024-12-08 16:45:11.872291254 +0800
+++ Dockerfile	2024-12-08 16:55:33.058956732 +0800
@@ -5,7 +5,7 @@
 # environment
 ENV ROOTFS=/root-out
 ENV REL=v3.21
-ENV ARCH=x86_64
+ENV ARCH=riscv64
 ENV MIRROR=http://dl-cdn.alpinelinux.org/alpine
 ENV PACKAGES=alpine-baselayout,\
 alpine-keys,\
@@ -31,7 +31,7 @@
 
 # set version for s6 overlay
 ARG S6_OVERLAY_VERSION="3.2.0.2"
-ARG S6_OVERLAY_ARCH="x86_64"
+ARG S6_OVERLAY_ARCH="riscv64"
 
 # add s6 overlay
 ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
@@ -54,8 +54,8 @@
 ARG PKG_INST_VERSION="v1"
 ARG LSIOWN_VERSION="v1"
 ARG WITHCONTENV_VERSION="v1"
-LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
-LABEL maintainer="TheLamer"
+LABEL build_version="Unofficial-docker-for-riscv version:- ${VERSION} Build-date:- ${BUILD_DATE}"
+LABEL maintainer="ngc7331"
 
 ADD --chmod=755 "https://raw.githubusercontent.com/linuxserver/docker-mods/mod-scripts/docker-mods.${MODS_VERSION}" "/docker-mods"
 ADD --chmod=755 "https://raw.githubusercontent.com/linuxserver/docker-mods/mod-scripts/package-install.${PKG_INST_VERSION}" "/etc/s6-overlay/s6-rc.d/init-mods-package-install/run"
